# Railway deployment configuration for PairMeUp API
# Database hosted on Neon, API only on Railway

[build]
cmd = "cd apps/api && npm ci && npm run build"

[deploy]
cmd = "cd apps/api && npm run start:prod"
healthcheck_path = "/health"

[env]
NODE_ENV = "production"
PORT = "$PORT"
DATABASE_URL = "$DATABASE_URL"
JWT_SECRET = "$JWT_SECRET"
ID_ENCRYPTION_KEY = "$ID_ENCRYPTION_KEY"
CORS_ORIGINS = "$CORS_ORIGINS"
GEODB_BASE_URL = "https://geodb-cities-api.wirefreethought.com"

# Optional PayPal configuration
PAYPAL_CLIENT_ID = "$PAYPAL_CLIENT_ID"
PAYPAL_CLIENT_SECRET = "$PAYPAL_CLIENT_SECRET"
PAYPAL_ENV = "sandbox"
