// Mock search API response for testing frontend
export const mockSearchResponse = {
  listings: [
    {
      id: '1',
      title: 'Apple AirPods Pro (2nd generation) - Like New',
      description: 'Excellent condition AirPods Pro with all original accessories. Noise cancellation works perfectly.',
      price: 199.99,
      currency: 'USD',
      condition: 'LIKE_NEW',
      images: ['/placeholder-airpods-pro.jpg'],
      brand: { id: '1', name: 'Apple' },
      model: { id: '1', name: 'AirPods Pro (2nd generation)' },
      city: { id: '1', name: 'New York' },
      seller: { 
        id: '1', 
        name: 'John Doe', 
        isVerified: true,
        averageRating: 4.8 
      },
      isVerified: true,
      createdAt: '2024-01-15T10:30:00Z',
    },
    {
      id: '2',
      title: 'Samsung Galaxy Buds2 Pro - Brand New',
      description: 'Unopened Samsung Galaxy Buds2 Pro in original packaging. Great for Android users.',
      price: 149.99,
      currency: 'USD',
      condition: 'NEW',
      images: ['/placeholder-galaxy-buds.jpg'],
      brand: { id: '2', name: 'Samsung' },
      model: { id: '2', name: 'Galaxy Buds2 Pro' },
      city: { id: '2', name: 'Los Angeles' },
      seller: { 
        id: '2', 
        name: 'Jane Smith', 
        isVerified: true,
        averageRating: 4.9 
      },
      isVerified: true,
      createdAt: '2024-01-14T15:45:00Z',
    },
    {
      id: '3',
      title: 'Sony WF-1000XM4 True Wireless Earbuds',
      description: 'Industry-leading noise canceling earbuds. Excellent sound quality and battery life.',
      price: 179.99,
      currency: 'USD',
      condition: 'GOOD',
      images: ['/placeholder-sony-wf.jpg'],
      brand: { id: '3', name: 'Sony' },
      model: { id: '3', name: 'WF-1000XM4' },
      city: { id: '3', name: 'Chicago' },
      seller: { 
        id: '3', 
        name: 'Mike Johnson', 
        isVerified: false,
        averageRating: 4.5 
      },
      isVerified: false,
      createdAt: '2024-01-13T09:20:00Z',
    },
    {
      id: '4',
      title: 'Bose QuietComfort Earbuds - New in Box',
      description: 'Brand new Bose QuietComfort Earbuds with amazing noise cancellation technology.',
      price: 199.99,
      currency: 'USD',
      condition: 'NEW',
      images: ['/placeholder-bose-qc.jpg'],
      brand: { id: '4', name: 'Bose' },
      model: { id: '4', name: 'QuietComfort Earbuds' },
      city: { id: '4', name: 'Houston' },
      seller: { 
        id: '4', 
        name: 'Sarah Wilson', 
        isVerified: true,
        averageRating: 4.7 
      },
      isVerified: true,
      createdAt: '2024-01-12T14:10:00Z',
    },
    {
      id: '5',
      title: 'Apple AirPods (3rd generation) - Good Condition',
      description: 'Well-maintained AirPods with spatial audio. All functions work perfectly.',
      price: 129.99,
      currency: 'USD',
      condition: 'GOOD',
      images: ['/placeholder-airpods-3.jpg'],
      brand: { id: '1', name: 'Apple' },
      model: { id: '5', name: 'AirPods (3rd generation)' },
      city: { id: '5', name: 'Phoenix' },
      seller: { 
        id: '5', 
        name: 'David Brown', 
        isVerified: false,
        averageRating: 4.2 
      },
      isVerified: false,
      createdAt: '2024-01-11T11:30:00Z',
    },
    {
      id: '6',
      title: 'JBL Live Pro 2 - Great Deal',
      description: 'Excellent value earbuds with adaptive noise cancelling. Perfect for workouts.',
      price: 89.99,
      currency: 'USD',
      condition: 'GOOD',
      images: ['/placeholder-jbl-live.jpg'],
      brand: { id: '6', name: 'JBL' },
      model: { id: '6', name: 'Live Pro 2' },
      city: { id: '6', name: 'Philadelphia' },
      seller: { 
        id: '1', 
        name: 'John Doe', 
        isVerified: true,
        averageRating: 4.8 
      },
      isVerified: true,
      createdAt: '2024-01-10T16:45:00Z',
    },
  ],
  total: 6,
  page: 1,
  totalPages: 1,
  hasMore: false,
};

export const mockFacetsResponse = {
  brands: [
    { id: '1', name: 'Apple', count: 2 },
    { id: '2', name: 'Samsung', count: 1 },
    { id: '3', name: 'Sony', count: 1 },
    { id: '4', name: 'Bose', count: 1 },
    { id: '6', name: 'JBL', count: 1 },
  ],
  models: [
    { id: '1', name: 'AirPods Pro (2nd generation)', count: 1 },
    { id: '2', name: 'Galaxy Buds2 Pro', count: 1 },
    { id: '3', name: 'WF-1000XM4', count: 1 },
    { id: '4', name: 'QuietComfort Earbuds', count: 1 },
    { id: '5', name: 'AirPods (3rd generation)', count: 1 },
    { id: '6', name: 'Live Pro 2', count: 1 },
  ],
  conditions: [
    { value: 'NEW', label: 'New', count: 2 },
    { value: 'LIKE_NEW', label: 'Like New', count: 1 },
    { value: 'GOOD', label: 'Good', count: 3 },
    { value: 'FAIR', label: 'Fair', count: 0 },
    { value: 'PARTS_ONLY', label: 'Parts Only', count: 0 },
  ],
  cities: [
    { id: '1', name: 'New York', count: 1 },
    { id: '2', name: 'Los Angeles', count: 1 },
    { id: '3', name: 'Chicago', count: 1 },
    { id: '4', name: 'Houston', count: 1 },
    { id: '5', name: 'Phoenix', count: 1 },
    { id: '6', name: 'Philadelphia', count: 1 },
  ],
  priceRanges: [
    { min: 0, max: 100, count: 1 },
    { min: 100, max: 150, count: 2 },
    { min: 150, max: 200, count: 3 },
    { min: 200, max: 300, count: 0 },
  ],
};
