#!/usr/bin/env bash
set -euo pipefail

# Usage:
# ADMIN_API_URL="https://pairmeup.onrender.com" ADMIN_EMAIL="admin@earbudhub.com" ADMIN_PASS="AdminPass123!" ./scripts/test/admin_approve_flow.sh

API_URL="${ADMIN_API_URL:-https://pairmeup.onrender.com}"
EMAIL="${ADMIN_EMAIL:-admin@earbudhub.com}"
PASSWORD="${ADMIN_PASS:-AdminPass123!}"

TEMP_BRAND_NAME="TestTempBrand-$(date +%s)"
TEMP_MODEL_NAME="TestTempModel-$(date +%s)"

echo "Using API: $API_URL"

# 1) Login as admin and obtain token
LOGIN_TOKEN=$(curl -sS -X POST "$API_URL/auth/login" -H 'Content-Type: application/json' -d "{\"email\":\"$EMAIL\",\"password\":\"$PASSWORD\"}" | jq -r '.access_token')
if [[ "$LOGIN_TOKEN" == "null" || -z "$LOGIN_TOKEN" ]]; then
  echo "Login failed; output from login may not include a token; aborting"
  echo "Full login output: $(curl -sS -X POST "$API_URL/auth/login" -H 'Content-Type: application/json' -d "{\"email\":\"$EMAIL\",\"password\":\"$PASSWORD\"}")"
  exit 1
fi

echo "Logged in; got token"

# 2) Create a listing as admin using a custom brand/model to generate a proposed brand/model and temp brand/model
CREATE_LISTING_RESPONSE=$(curl -sS -X POST "$API_URL/listings" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $LOGIN_TOKEN" \
  -d @- <<JSON
{
  "title": "Test listing for admin_approve_flow",
  "description": "A test listing to create a proposed brand/model entry for admin approval flow",
  "type": "SELL",
  "condition": "USED",
  "price": 1,
  "currency": "USD",
  "cityId": null,
  "customBrand": "$TEMP_BRAND_NAME",
  "customModel": "$TEMP_MODEL_NAME",
  "images": []
}
JSON
)

LISTING_ID=$(echo "$CREATE_LISTING_RESPONSE" | jq -r '.id')
if [[ "$LISTING_ID" == "null" || -z "$LISTING_ID" ]]; then
  echo "Create listing failed. See response: $CREATE_LISTING_RESPONSE"
  exit 1
fi

echo "Created listing: $LISTING_ID; waiting briefly for proposed brand to be created..."
sleep 2

# 3) Get proposed brands via admin endpoint; find the proposed brand with our custom name
PROPOSED_LIST=$(curl -sS -X GET "$API_URL/admin/proposed-brands" -H "Authorization: Bearer $LOGIN_TOKEN")

PROPOSED_ID=$(echo "$PROPOSED_LIST" | jq -r --arg name "$TEMP_BRAND_NAME" '.data[] | select(.name == $name) | .id')
if [[ -z "$PROPOSED_ID" ]]; then
  echo "Proposed brand not found in admin list. Dumping output for debug:"
  echo "$PROPOSED_LIST" | jq .
  exit 1
fi

echo "Proposed brand found: $PROPOSED_ID"

# 4) Approve the proposed brand as canonical (createCanonical: true) with optional edited fields
APPROVE_RESPONSE=$(curl -sS -X POST "$API_URL/admin/proposed-brands/$PROPOSED_ID/approve" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $LOGIN_TOKEN" \
  -d '{"createCanonical": true, "name": "Autogenerated-Canonical-'$TEMP_BRAND_NAME'", "description": "Approved via script", "website": "https://example.test"}')

echo "Approve response: $APPROVE_RESPONSE" | jq .

# 5) Verify the brand was created/updated
CANONICAL_BRAND_NAME=$(echo "$APPROVE_RESPONSE" | jq -r '.canonicalBrand.name // empty')
CANONICAL_BRAND_ID=$(echo "$APPROVE_RESPONSE" | jq -r '.canonicalBrand.id // empty')

if [[ -n "$CANONICAL_BRAND_ID" ]]; then
  echo "Canonical brand created: $CANONICAL_BRAND_NAME ($CANONICAL_BRAND_ID)"
else
  echo "Canonical brand not present in response; script may still have succeeded; attempt to lookup in public brands..."
  CANONICAL_BRAND_LOOKUP=$(curl -sS -X GET "$API_URL/brands?search=$TEMP_BRAND_NAME" -H "Authorization: Bearer $LOGIN_TOKEN")
  echo "$CANONICAL_BRAND_LOOKUP" | jq .
fi

# 6) Validate listing's brand was migrated to the canonical brand (if created)
LISTING_AFTER=$(curl -sS -X GET "$API_URL/listings/$LISTING_ID" -H "Authorization: Bearer $LOGIN_TOKEN")
LISTING_BRAND_ID=$(echo "$LISTING_AFTER" | jq -r '.brand.id // empty')

if [[ -n "$CANONICAL_BRAND_ID" && "$LISTING_BRAND_ID" == "$CANONICAL_BRAND_ID" ]]; then
  echo "Listing brand updated to canonical: $LISTING_BRAND_ID"
else
  echo "Listing brand ID differs from canonical (or canonical not created). Listing brand id: $LISTING_BRAND_ID. Canonical id: $CANONICAL_BRAND_ID"
  echo "Listing response: $LISTING_AFTER" | jq .
fi

# Done
exit 0
